# Generated by Django 4.2.7 on 2023-11-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeluploads',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='modeluploads',
            name='file_size',
            field=models.CharField(default='something', max_length=200),
        ),
    ]
