# Generated by Django 4.2.7 on 2023-11-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsapp', '0002_rename_filename_modeluploads_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluploads',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
