# Generated by Django 4.2.7 on 2023-11-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsapp', '0004_remove_modeluploads_is_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluploads',
            name='file_size',
            field=models.CharField(max_length=200),
        ),
    ]
