# Generated by Django 4.2.6 on 2023-12-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsapp', '0005_alter_modeluploads_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluploads',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
